services:
  db:
    image: postgres:16-alpine3.20
    container_name: gn-authentication-service-db
    restart: always
    environment:
      - POSTGRES_USER=postgress
      - POSTGRES_PASSWORD=postgress
      - POSTGRES_DB=gn-authentication-service
    ports:
      - '5439:5432'
    volumes:
      - authentication_service_pgdata:/var/lib/postgresql/data

volumes:
  authentication_service_pgdata: