server:
  port: ${GATEWAY_PORT:8080}

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: authentication-service
              uri: http://localhost:${AUTH_SERVICE_PORT:8082}
              predicates:
                - Path=/api/v1/authentication/**

            - id: user-service
              uri: http://localhost:${USER_SERVICE_PORT:8081}
              predicates:
                - Path=/api/v1/users/**

            - id: restaurant-service
              uri: http://localhost:${RESTAURANT_SERVICE_PORT:8083}
              predicates:
                - Path=/api/v1/restaurants/**,/api/v1/meals/**,/api/v1/reviews/**,/api/v1/meal-categories/**

            - id: reservation-service
              uri: http://localhost:${RESERVATION_SERVICE_PORT:8084}
              predicates:
                - Path=/api/v1/reservations/**,/api/v1/restaurant-tables/**,/api/v1/floor-schema/**

            - id: order-service
              uri: http://localhost:${ORDER_SERVICE_PORT:8085}
              predicates:
                - Path=/api/v1/orders/**

            - id: payment-service
              uri: http://localhost:${PAYMENT_SERVICE_PORT:8086}
              predicates:
                - Path=/api/v1/payments/**

            - id: notification-service
              uri: http://localhost:${NOTIFICATION_SERVICE_PORT:8087}
              predicates:
                - Path=/api/v1/notifications/**

logging:
  pattern:
    correlation: "[${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

management:
  tracing:
    sampling:
      probability: 1

jwt:
  secret: ${JWT_SECRET}

exception:
  dto-factory:
    service-id: api-gateway
