#Rest client
rest.client.user-service.baseUrl=http://localhost:8081
rest.client.authentication-service.baseUrl=http://localhost:8082
rest.client.restaurant-service.base-url=http://localhost:8083
rest.client.reservation-service.base-url=http://localhost:8084
rest.client.order-service.base-url=http://localhost:8085
rest.client.payment-service.base-url=http://localhost:8086
rest.client.notification-service.base-url=http://localhost:8087
rest.client.invoice-service.base-url=http://localhost:8089

spring.application.name=api-gateway
exception.dto-factory.serviceId=api-gateway
#Jwt
jwt.secret=klsegjwejgk2893thg395hubgiwbfvowi90KJNBEHVIWUACJU876bnkjh
#TraceId
logging.pattern.correlation=[${spring.application.name:},%X{traceId:-},%X{spanId:-}]
management.tracing.sampling.probability=1