#Application
server.port=8087
spring.application.name=notification-service
#Rest client
rest.client.user-service.baseUrl=http://localhost:8081
#DataSource
spring.datasource.url=jdbc:postgresql://<HOST>:<PORT>/<DB_NAME>
spring.datasource.username=<DB_USER>
spring.datasource.password=<DB_PASSWORD>
spring.datasource.driver-class-name=org.postgresql.Driver
#Hibenate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#Liquibase
spring.liquibase.changelog=classpath:notification-service-db/changelog.xml
#Custom starter properties
exception.dto-factory.serviceId=notification-service
#TraceId
logging.pattern.correlation=[${spring.application.name:},%X{traceId:-},%X{spanId:-}]
management.tracing.sampling.probability=1
#Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=maskevich_vi_22@mf.grsu.by
spring.mail.password=alcs kbdc urbu efpd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
#Kafka
notification-service.consumer.kafka-topic=payments
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=notification-service
spring.kafka.consumer.auto-offset-reset=latest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
#Scheduler
notification-service.scheduler.enabled=true
notification-service.scheduler.fixed-delay=10000
notification-service.scheduler.initial-delay=15000
notification-service.scheduler.lock-at-most-for=2m
#Verification code
notification-service.verification-code.expiration-time-seconds=90
#CodeHasher
notification-service.code-hasher.otp-secret=${OTP_SECRET}