services:
  db:
    image: postgres:16-alpine3.20
    container_name: gn-user-service-db
    restart: always
    environment:
      - POSTGRES_USER=postgress
      - POSTGRES_PASSWORD=postgress
      - POSTGRES_DB=gn-user-service
    ports:
      - '5433:5432'
    volumes:
      - user_service_pgdata:/var/lib/postgresql/data

volumes:
  user_service_pgdata: