#Application
server.port=8086
spring.application.name=payment-service
#Rest client
rest.client.order-service.base-url=http://localhost:8085
rest.client.bonus-service.base-url=http://localhost:8088
rest.client.reservation-service.base-url=http://localhost:8084
#DataSource
spring.datasource.url=jdbc:postgresql://<HOST>:<PORT>/<DB_NAME>
spring.datasource.username=<DB_USER>
spring.datasource.password=<DB_PASSWORD>
spring.datasource.driver-class-name=org.postgresql.Driver
#Hibenate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#Liquibase
spring.liquibase.changelog=classpath:payment-service-db/changelog.xml
#Custom starter properties
exception.dto-factory.serviceId=payment-service
#TraceId
logging.pattern.correlation=[${spring.application.name:},%X{traceId:-},%X{spanId:-}]
management.tracing.sampling.probability=1
#Payment
payment.service.prepayment-percentage=0.10
#Kafka
common.outbox.producer.kafka-topic=payments
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
#Scheduler
common.outbox.scheduler.lock-at-most-for=2m
common.outbox.scheduler.initial-delay=10000
common.outbox.scheduler.fixed-delay=5000
common.outbox.scheduler.enabled=true
