#DataSource
spring.datasource.url=jdbc:postgresql://localhost:5436/gn-payment-service
spring.datasource.username=postgress
spring.datasource.password=postgress
spring.datasource.driver-class-name=org.postgresql.Driver