#Application
server.port=8089
spring.application.name=invoice-service
#Custom starter properties
exception.dto-factory.serviceId=invoice-service
#TraceId
logging.pattern.correlation=[${spring.application.name:},%X{traceId:-},%X{spanId:-}]
management.tracing.sampling.probability=1