#Application
server.port=8081
spring.application.name=user-service
#DataSource
spring.datasource.url=jdbc:postgresql://<HOST>:<PORT>/<DB_NAME>
spring.datasource.username=<DB_USER>
spring.datasource.password=<DB_PASSWORD>
spring.datasource.driver-class-name=org.postgresql.Driver
#Hibenate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#Liquibase
spring.liquibase.changelog=classpath:user-service-db/changelog.xml
#Custom starter properties
exception.dto-factory.serviceId=user-service
#TraceId
logging.pattern.correlation=[${spring.application.name:},%X{traceId:-},%X{spanId:-}]
management.tracing.sampling.probability=1
#Kafka
common.outbox.producer.kafka-topic=users
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
#Scheduler
common.outbox.scheduler.lock-at-most-for=2m
common.outbox.scheduler.initial-delay=10000
common.outbox.scheduler.fixed-delay=2000
common.outbox.scheduler.enabled=true