#DataSource
spring:
  datasource:
    url: ${AUTH_DB_URL:jdbc:postgresql://localhost:5439/gn-authentication-service}
    username: ${AUTH_DB_USERNAME:postgress}
    password: ${AUTH_DB_PASSWORD:postgress}