#Application
server.port=8082
spring.application.name=authentication-service
#DataSource
spring.datasource.url=jdbc:postgresql://<HOST>:<PORT>/<DB_NAME>
spring.datasource.username=<DB_USER>
spring.datasource.password=<DB_PASSWORD>
spring.datasource.driver-class-name=org.postgresql.Driver
#Hibenate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#Liquibase
spring.liquibase.changelog=classpath:authentication-service-db/changelog.xml
#Custom starter properties
exception.dto-factory.serviceId=authentication-service
#Jwt
jwt.secret=klsegjwejgk2893thg395hubgiwbfvowi90KJNBEHVIWUACJU876bnkjh
    #10 minutes
jwt.access-token.expiration-time=600000
    #24 hours
jwt.refresh-token.expiration-time=86400000
#TraceId
logging.pattern.correlation=[${spring.application.name:},%X{traceId:-},%X{spanId:-}]
management.tracing.sampling.probability=1
#Scheduler
scheduler.cron.interval= 0 0 */12 * * *
scheduler.fixedDelay=15000
scheduler.fixedRate=20000