#DataSource
spring.datasource.url=jdbc:postgresql://localhost:5437/gn-reservation-service
spring.datasource.username=postgress
spring.datasource.password=postgress
spring.datasource.driver-class-name=org.postgresql.Driver