#Application
server.port=8083
spring.application.name=restaurant-service
#DataSource
spring.datasource.url=jdbc:postgresql://<HOST>:<PORT>/<DB_NAME>
spring.datasource.username=<DB_USER>
spring.datasource.password=<DB_PASSWORD>
spring.datasource.driver-class-name=org.postgresql.Driver
#Hibenate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#Liquibase
spring.liquibase.changelog=classpath:restaurant-service-db/changelog.xml
#Custom starter properties
exception.dto-factory.serviceId=restaurant-service
#TraceId
logging.pattern.correlation=[${spring.application.name:},%X{traceId:-},%X{spanId:-}]
management.tracing.sampling.probability=1